[phases.setup]
cmds = ["npm install -g pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd ../.. && pnpm install --no-frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd ../.. && pnpm --filter @skyplanner/web build"]

[start]
cmd = "sh -c \"HOST=0.0.0.0 node dist/server/entry.mjs\""
